# Generated by Django 5.2.5 on 2025-08-22 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#5e72e4', max_length=7),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='history',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='habit', max_length=10),
        ),
    ]
